version: "2"

run:
  timeout: 5m

issues:
  new: true
  exclude-dirs:
    - .*\.pb\.go$

linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - whitespace
  disable:
    - errcheck
    - goprintffuncname
    - gosimple
    - nilerr
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unparam
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/p4gefau1t/trojan-go)
  goimports:
    local-prefixes: github.com/p4gefau1t/trojan-go
